#!/bin/sh
uci set network.lan.ipaddr="10.0.0.1"
uci commit network
/etc/init.d/network restart
sed -i "/^DISTRIB_DESCRIPTION='/s/'$/ Compiled by Vic Hu'/" /etc/openwrt_release
[ -d "/etc/init.d" ] && chmod +x /etc/init.d/*

